# Generated by Django 5.2.6 on 2025-09-13 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('preguntas', models.TextField(help_text='JSON con preguntas y respuestas')),
                ('tema', models.CharField(max_length=80)),
                ('nivel_dificultad', models.CharField(default='Medio', max_length=10)),
                ('puntos_base', models.IntegerField(default=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ReaccionReto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reaccion', models.CharField(default='Like', max_length=20)),
                ('fecha_reaccion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Retos.reto')),
            ],
            options={
                'unique_together': {('reto', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='ProgresoReto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_obtenidos', models.IntegerField()),
                ('tiempo_segundos', models.IntegerField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Retos.reto')),
            ],
            options={
                'unique_together': {('usuario', 'reto')},
            },
        ),
    ]
