# Generated by Django 5.2.6 on 2025-09-13 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(blank=True, max_length=80, null=True)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('correo_electronico', models.EmailField(max_length=120, unique=True)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('tipo_usuario', models.CharField(blank=True, help_text='Estudiante, Docente, Familiar, Comunidad', max_length=20, null=True)),
                ('institucion_educativa', models.CharField(blank=True, max_length=200, null=True)),
                ('comunidad', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('localizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalogos.localizacion')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Catalogos.rol')),
            ],
        ),
    ]
