# Generated by Django 5.2.6 on 2025-09-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=400, null=True)),
                ('tipo', models.CharField(help_text='Memoria, Saber, Evento', max_length=30)),
            ],
            options={
                'unique_together': {('nombre', 'tipo')},
            },
        ),
    ]
