# Generated by Django 5.2.6 on 2025-09-13 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalogos', '0002_categoria'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaberPopular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('tipo_saber', models.CharField(max_length=50)),
                ('estado', models.CharField(default='Pendiente', max_length=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saberes_aprobados', to='Usuarios.usuario')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalogos.categoria')),
                ('localizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalogos.localizacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioSaber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=600)),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Activo', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
                ('saber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Saberes.saberpopular')),
            ],
        ),
        migrations.CreateModel(
            name='ReaccionSaber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reaccion', models.CharField(default='Like', max_length=20)),
                ('fecha_reaccion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
                ('saber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Saberes.saberpopular')),
            ],
            options={
                'unique_together': {('saber', 'usuario')},
            },
        ),
    ]
