# Generated by Django 5.2.6 on 2025-09-13 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalogos', '0002_categoria'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Pendiente', max_length=12)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('es_publico', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memorias_aprobadas', to='Usuarios.usuario')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalogos.categoria')),
                ('localizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalogos.localizacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_medio', models.CharField(max_length=20)),
                ('url_archivo', models.CharField(blank=True, max_length=1000, null=True)),
                ('contenido_texto', models.TextField(blank=True, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('memoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Memorias.memoria')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioMemoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=600)),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Activo', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
                ('memoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Memorias.memoria')),
            ],
        ),
        migrations.CreateModel(
            name='ReaccionMemoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reaccion', models.CharField(default='Like', max_length=20)),
                ('fecha_reaccion', models.DateTimeField(auto_now_add=True)),
                ('memoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Memorias.memoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
            ],
            options={
                'unique_together': {('memoria', 'usuario')},
            },
        ),
    ]
